# -*- coding: utf-8 -*-
"""customer_churn_pyspark

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GdgPdmDxCR0hGa2Z3aO2jNnMhLx5tgQ2
"""

from pyspark.sql import SparkSession
from pyspark.sql import functions as F

spark = SparkSession.builder.appName("customer_churn").getOrCreate()

df = (
    spark.read
    .option("header", True)
    .option("inferSchema", True)
    .csv("/content/drive/MyDrive/Customer_Churn_Data.csv")
)

type(df)

df.printSchema()

df.show(5)

df.summary().show()

df.count()

len(df.columns)

total = df.count()
distinct = df.distinct().count()

print(total - distinct)

df=df.drop('AccountID')    # dropping a column

len(df.columns)

type(df)

df.select('Tenure').distinct().count()    # unique values and count

# finding null values
df.select(
    F.sum(F.col('Tenure').isNull().cast('int')).alias('Tenure_null_count')
).show()

df.filter(F.col("Tenure").isNull()).count()

# finding mode
tenure_mode = (
    df.groupby('Tenure')
    .count()
    .orderBy(F.desc('count'))
    .first()[0]
)

tenure_mode

df.fillna({'Tenure': tenure_mode})

df.filter(F.col("Tenure").isNull()).count()

df.select('Churn').distinct().show()   # unique values show

# Finding average
df.select(F.avg('CC_Contacted_LY')).show()

df=df.replace({'M':'Male', 'F':'Female'}, subset=['Gender'])
df.show()

type(df)

from pyspark.sql import functions as F

df = df.withColumn(
    "Gender",
    F.when(F.col("Gender") == "M", "Male")
     .when(F.col("Gender") == "F", "Female")
     .otherwise(F.col("Gender"))
)

## Finding median
df.approxQuantile("CC_Contacted_LY", [0.5],0.25)

df.select('Tenure').distinct().show()

df=df.replace({'#':'1'},subset=['Tenure'])

df=df.dropna()

from pyspark.sql import functions as F

df = df.withColumn(
    "Tenure",
    F.col("Tenure").cast("int")
)

df.printSchema()

num_cols = [
 'Tenure',
 'City_Tier',
 'CC_Contacted_LY',
 'Service_Score',
 'CC_Agent_Score',
 'Complain_ly']

pdf = df.select(num_cols).toPandas()

import matplotlib.pyplot as plt

pdf.hist(figsize=(20,18), bins=30)
plt.tight_layout()
plt.show()

len(df.columns)

df.printSchema()

"""### Scaling"""

num_cols = [
 'Tenure',
 'City_Tier',
 'CC_Contacted_LY',
 'Service_Score',
 'CC_Agent_Score',
 'Complain_ly']

## Assemble numerical columns into a vector

from pyspark.ml.feature import VectorAssembler, StandardScaler
from pyspark.ml.functions import vector_to_array
from pyspark.sql import functions as F

assembler = VectorAssembler(
    inputCols=num_cols,
    outputCol="num_features"
)

df_vec = assembler.transform(df)

len(df_vec.columns)

## Apply Z-score scaling (StandardScaler)

from pyspark.ml.feature import StandardScaler

scaler = StandardScaler(
    inputCol="num_features",
    outputCol="scaled_features",
    withMean=True,
    withStd=True
)

scaler_model = scaler.fit(df_vec)
df_scaled_vec = scaler_model.transform(df_vec)

len(df_scaled_vec.columns)

df_scaled_vec.printSchema()

## Convert vector back to individual columns (KEY STEP)

from pyspark.ml.functions import vector_to_array

df_scaled_arr = df_scaled_vec.withColumn(
    "scaled_array",
    vector_to_array("scaled_features")
)

## Add scaled columns back (Spark equivalent of concat)

for i, col in enumerate(num_cols):
    df_scaled_arr = df_scaled_arr.withColumn(
        f"{col}_scaled",
        F.col("scaled_array")[i]
    )

len(df_scaled_arr.columns)

df_scaled_arr.printSchema()

df_scaled = df_scaled_arr.drop('Tenure', 'City_Tier', 'CC_Contacted_LY', 'Service_Score', 'CC_Agent_Score', 'Complain_ly', 'num_features' , 'scaled_features', 'scaled_array')

len(df_scaled.columns)

df_scaled.printSchema()

"""### Data encoding"""

from pyspark.ml.feature import StringIndexer, OneHotEncoder
from pyspark.ml import Pipeline

cat_cols1 = [c for c, t in df_scaled.dtypes if t == "string"]
cat_cols1

cat_cols = ['Gender','Marital_Status','Login_device','Payment','account_segment']

indexers = [
    StringIndexer(
        inputCol=c,
        outputCol=f"{c}_idx",
        handleInvalid="keep"
    )
    for c in cat_cols
]

encoder = OneHotEncoder(
    inputCols=[f"{c}_idx" for c in cat_cols],
    outputCols=[f"{c}_ohe" for c in cat_cols],
    dropLast=True
)

pipeline = Pipeline(stages=indexers + [encoder])

df_ohe = pipeline.fit(df_scaled).transform(df_scaled)

## creates a list of StringIndexer transformers, one per categorical column.

indexers = [
    StringIndexer(
        inputCol=c,
        outputCol=f"{c}_idx",
        handleInvalid="keep"
    )
    for c in cat_cols
]

## Converts indexed categorical columns → one-hot encoded vectors

encoder = OneHotEncoder(
    inputCols=[f"{c}_idx" for c in cat_cols],
    outputCols=[f"{c}_ohe" for c in cat_cols],
    dropLast=True
)



















































