name: ML CI Pipeline

on: [push]

jobs:
  churn-model:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: pip install pandas pyspark scikit-learn

    - name: Run churn model
      run: python customer_churn_pyspark.py
